# Generated by Django 5.2.7 on 2025-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_deuda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='saldada',
            field=models.BooleanField(default=False),
        ),
    ]
